/** Copy for the reserves section of the raid detail page. */

export const RESERVES = {
  heading: 'Loot reserves',
  lede: 'One hard and one soft reserve each, on different items. If anyone hard-reserved a drop, only they roll for it; if not, soft reserves roll; otherwise it is an open roll.',
  locksAt: 'Reserves lock',
  locked: 'Reserves are locked. Officers can still change them.',
  cancelled: 'This raid was cancelled.',
  notEligible: 'Sign up as Accept or Tentative to reserve.',
  noCharacter: 'Add a character on the roster to reserve.',
  forWhom: 'Reserves for',
  you: (name: string) => `${name} (you)`,
  character: 'Character',
  hr: 'Hard reserve',
  sr: 'Soft reserve',
  none: 'None',
  search: 'Search items…',
  noMatches: 'No items match. Try another name.',
  trash: 'Trash',
  shared: 'Shared',
  otherPick: 'chosen in the other reserve',
  resultCount: (count: number) => `${count} items found`,
  pickerCounts: (hr: number, sr: number) => `HR ${hr}, SR ${sr}`, 
  blocked: 'already won with HR',
  counts: (hr: number, sr: number) => (hr || sr ? `HR ${hr}, SR ${sr} · ` : ''),
  yours: 'yours',
  editing: 'editing',
  ownPick: (kind: 'HR' | 'SR', name: string | null) => `${name === null ? 'your' : `${name}'s`} ${kind} · `,
  save: 'Save reserves',
  clear: 'Clear',
  saved: 'Reserves saved',
  savedFor: (name: string) => `Saved ${name}'s reserves`,
  cleared: 'Reserves cleared',
  sameItem: 'Pick two different items.',
  listHeading: 'Who reserved what',
  listEmpty: 'No reserves yet.',
  hrShort: 'HR',
  srShort: 'SR',
};
