/** Copy for the reserves section of the raid detail page. */
import { REASONS } from '@/lib/loot-rules';

export const RESERVES = {
  heading: 'Loot reserves',
  /** Followed by the lock time and a full stop. */
  lede: 'You may select one hard and one soft reserve per raid, on different items. Reserves for this raid will lock at',
  locked: 'Reserves are locked. Please contact an officer to request a change.',
  lockedOfficer: 'Reserves are locked. As an officer, you can still change them.',
  cancelled: 'This raid was cancelled.',
  notEligible: 'You must be signed up for this raid to reserve items.',
  noCharacter: 'Add a character on the roster to reserve.',
  forWhom: 'Reserves for',
  you: (name: string) => `${name} (you)`,
  character: 'Character',
  hr: 'Hard reserve',
  sr: 'Soft reserve',
  /** Previously won by this character, not an officer's block (that is `notOpen`). */
  blocked: 'Previously won',
  /** An officer closed this item to reserves; the same words the reserve route refuses with. */
  notOpen: REASONS.itemBlocked,
  /** Under a saved pick on an item blocked after it was saved; the route keeps it until removed. */
  keptBlocked: `${REASONS.itemBlocked}. You can keep it or remove it.`,
  search: 'Search items',
  items: 'Items',
  choosingSlot: "Which reserve you're choosing",
  choosing: 'Choosing',
  notPicked: 'Not picked',
  noMatches: 'No items match. Try another name.',
  itemCount: (shown: number, total: number) => `${shown} of ${total} items`,
  details: 'Item details',
  detailsEmpty: 'Select an item to see who reserved it.',
  trash: 'Trash',
  shared: 'Shared',
  dropsFrom: (names: string) => `Drops from ${names}`,
  choose: (kind: 'HR' | 'SR') => `Choose as ${kind === 'HR' ? 'hard' : 'soft'} reserve`,
  picked: (kind: 'HR' | 'SR') => `Picked as ${kind}`,
  pickedDetails: (kind: 'HR' | 'SR', name: string | null) => `Picked as ${name === null ? 'your' : `${name}'s`} ${kind === 'HR' ? 'hard' : 'soft'} reserve`,
  /** `name` is null when choosing for yourself. */
  otherSlot: (kind: 'HR' | 'SR', name: string | null) => `${name === null ? 'Your' : `${name}'s`} ${kind === 'HR' ? 'hard' : 'soft'} reserve`,
  ineligible: 'This item is ineligible to be reserved for this raid.',
  remove: 'Remove',
  yours: 'yours',
  editing: 'editing',
  save: 'Save reserves',
  yourReserves: 'Your reserves',
  none: "You haven't picked reserves for this raid.",
  noPick: 'None',
  pick: 'Pick reserves',
  change: 'Change reserves',
  /** The reserves window. */
  title: 'Pick your reserves',
  titleFor: (name: string) => `Pick reserves for ${name}`,
  /** Followed by the lock time and a full stop. */
  windowLede: 'Please select one hard and one soft reserve item. They must be separate items. You can change your selection until',
  notNow: 'Not now',
  cancel: 'Cancel',
  undo: 'Undo',
  saved: 'Reserves saved',
  savedFor: (name: string) => `Saved ${name}'s reserves`,
  cleared: 'Reserves cleared',
  sameItem: 'Pick two different items.',
  reservedForRaid: 'reserved for this raid',
  reservedBy: 'Currently reserved by',
  noOne: 'No one has reserved this yet.',
  /** Read after the visible "HR 4" on a count pill. */
  showNames: (kind: 'HR' | 'SR', count: number, item: string) => ` ${kind === 'HR' ? 'hard' : 'soft'} reserve${count === 1 ? '' : 's'} for ${item}: show names`,
  listHeading: 'Who reserved what',
  showList: (count: number) => `Show who reserved what · ${count} ${count === 1 ? 'item' : 'items'}`,
  hideList: 'Hide who reserved what',
  listEmpty: 'No reserves yet.',
  hrShort: 'HR',
  srShort: 'SR',
};
