/** Copy for the reserves section of the raid detail page. */

export const RESERVES = {
  heading: 'Loot reserves',
  lede: 'One hard and one soft reserve each, on different items. If anyone hard-reserved a drop, only they roll for it; if not, soft reserves roll; otherwise it is an open roll.',
  locksAt: 'Reserves lock',
  locked: 'Reserves are locked. Officers can still change them.',
  cancelled: 'This raid was cancelled.',
  notEligible: 'Sign up as Accept or Tentative to reserve.',
  noCharacter: 'Add a character on the roster to reserve.',
  forWhom: 'Reserves for',
  you: (name: string) => `${name} (you)`,
  character: 'Character',
  hr: 'Hard reserve',
  sr: 'Soft reserve',
  blocked: 'Previously won',
  search: 'Search items',
  items: 'Items',
  choosingSlot: "Which reserve you're choosing",
  choosing: 'Choosing',
  notPicked: 'Not picked',
  noMatches: 'No items match. Try another name.',
  itemCount: (shown: number, total: number) => `${shown} of ${total} items`,
  details: 'Item details',
  detailsEmpty: 'Select an item to see who reserved it.',
  trash: 'Trash',
  shared: 'Shared',
  dropsFrom: (names: string) => `Drops from ${names}`,
  choose: (kind: 'HR' | 'SR') => `Choose as ${kind === 'HR' ? 'hard' : 'soft'} reserve`,
  picked: (kind: 'HR' | 'SR') => `Picked as ${kind}`,
  pickedDetails: (kind: 'HR' | 'SR', name: string | null) => `Picked as ${name === null ? 'your' : `${name}'s`} ${kind === 'HR' ? 'hard' : 'soft'} reserve`,
  otherSlot: (kind: 'HR' | 'SR') => `Your ${kind === 'HR' ? 'hard' : 'soft'} reserve`,
  ineligible: 'This item is ineligible to be reserved for this raid.',
  remove: 'Remove',
  yours: 'yours',
  editing: 'editing',
  save: 'Save reserves',
  saved: 'Reserves saved',
  savedFor: (name: string) => `Saved ${name}'s reserves`,
  cleared: 'Reserves cleared',
  sameItem: 'Pick two different items.',
  listHeading: 'Who reserved what',
  listEmpty: 'No reserves yet.',
  hrShort: 'HR',
  srShort: 'SR',
};
