import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { parseSeriesInput } from '@/lib/raid-series-rules';
import { runTick } from '@/lib/tick';
import { jsonBody, NO_STORE, requireOfficer } from '../../_officer';

/**
 * PATCH /api/raid-series/:id — "this and future raids" (SYNC-SPEC §9.3). The series changes;
 * future instances that are still unposted and not edited individually are dropped and
 * regenerated by tick from the new rule. Posted or detached instances keep what they have.
 * `{ active: false }` alone deactivates the series the same way.
 */
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireOfficer();
  if ('deny' in auth) return auth.deny;
  const { id } = await params;
  const existing = await db.raidSeries.findUnique({ where: { id } });
  if (!existing) return NextResponse.json({ error: 'No such series.' }, { status: 404, headers: NO_STORE });
  const body = (await jsonBody(request)) as Record<string, unknown> | null;
  const merged = { ...existing, notes: existing.notes ?? '', ...(body ?? {}) };
  const parsed = parseSeriesInput(merged);
  if (!parsed.ok) return NextResponse.json({ error: parsed.error }, { status: 400, headers: NO_STORE });

  const now = new Date();
  const dropped = await db.$transaction(async (tx) => {
    await tx.raidSeries.update({ where: { id }, data: parsed.value });
    const gone = await tx.raid.deleteMany({ where: { seriesId: id, status: 'SCHEDULED', startsAt: { gt: now }, postedAt: null, detached: false } });
    return gone.count;
  });
  const counts = parsed.value.active ? await runTick() : { generated: 0 };
  return NextResponse.json({ id, dropped, generated: counts.generated }, { headers: NO_STORE });
}
